title: wittawasw
description: >-
baseurl: ""
url: https://wittawasw.com
author:
  name: wittawasw

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-compose

exclude:
  - aboutme.md

markdown: kramdown
highlighter: rouge

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 7
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
