title: wittawasw
email: start@wittawasw.com
description: >-
  Software engineer. Ruby. Golang.
baseurl: ""
url: https://wittawasw.com
twitter_username: wittawasw
github_username:  wittawasw

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 7

