title: wittawasw
email: start@wittawasw.com
description: >-
baseurl: ""
url: https://wittawasw.com
twitter_username: wittawasw
github_username:  wittawasw
author:
  name: wittawasw

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-compose
  - jekyll-feed
  - jekyll-paginate

paginate: 7

