title: wittawasw
description: >-
baseurl: ""
url: https://wittawasw.com
author:
  name: wittawasw

# Build settings
theme: minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-compose

paginate: 7

markdown: kramdown
highlighter: rouge
